export interface Book {
    id: string,
    cover:string,
    title: string,
    author: string,
    price: number,
    rating: number,
    genre: string,
    description: string,
    year: number,
    dimensions: string,
    coverType: string,
    popular: boolean,
    new: boolean,
    promotion: boolean,
}
